// <auto-generated />
namespace Pims.Persistence.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class _createGenarelInformation : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_createGenarelInformation));
        
        string IMigrationMetadata.Id
        {
            get { return "202309051714563__createGenarelInformation"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
